# Generated by Django 5.1.3 on 2024-12-01 06:43

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'دیگر')], default='O', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('uniqueIdentifier', models.CharField(max_length=20)),
                ('chat_id_telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('seri_shenasname', models.CharField(blank=True, max_length=15, null=True)),
                ('seri_shenasname_char', models.CharField(blank=True, max_length=15, null=True)),
                ('serial_shenasname', models.CharField(blank=True, max_length=15, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('highschool', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], max_length=15, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=15, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=120, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sheba_number', models.CharField(blank=True, max_length=35, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
                ('country_prefix', models.CharField(blank=True, max_length=25, null=True, verbose_name='پیش شماره کشور')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('city_prefix', models.CharField(blank=True, max_length=15, null=True, verbose_name='پیش شماره شهر')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='بخش')),
                ('remnant_address', models.TextField(blank=True, null=True, verbose_name='ادامه آدرس')),
                ('alley', models.CharField(blank=True, max_length=100, null=True, verbose_name='کوچه')),
                ('plaque', models.CharField(blank=True, max_length=15, null=True, verbose_name='پلاک')),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='کد پستی')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('emergency_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن اضطراری')),
                ('emergency_tel_city_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='پیش شماره شهر تلفن اضطراری')),
                ('emergency_tel_country_prefix', models.CharField(blank=True, max_length=15, null=True, verbose_name='پیش شماره کشور تلفن اضطراری')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس')),
                ('fax_prefix', models.CharField(blank=True, max_length=15, null=True, verbose_name='پیش شماره فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('father_uniqueIdentifier', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='آدرس شرکت')),
                ('company_city_prefix', models.CharField(blank=True, max_length=15, null=True, verbose_name='پیش شماره شهر شرکت')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن شرکت')),
                ('company_postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='کد پستی شرکت')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل شرکت')),
                ('company_fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس شرکت')),
                ('company_fax_prefix', models.CharField(blank=True, max_length=15, null=True, verbose_name='پیش شماره فکس شرکت')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان شغل')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='شرح شغل')),
                ('company_web_site', models.TextField(blank=True, null=True, verbose_name='ادرس شرکت')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('is_current', models.BooleanField(default=True, verbose_name='شغل فعلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اطلاعات شغلی',
                'verbose_name_plural': 'اطلاعات شغلی',
            },
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_country', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('economic_code', models.CharField(blank=True, max_length=150, null=True)),
                ('evidence_expiration_date', models.CharField(blank=True, max_length=150, null=True)),
                ('evidence_release_company', models.CharField(blank=True, max_length=150, null=True)),
                ('evidence_release_date', models.CharField(blank=True, max_length=150, null=True)),
                ('legal_person_type_sub_category', models.CharField(blank=True, max_length=150, null=True)),
                ('register_date', models.CharField(blank=True, max_length=150, null=True)),
                ('legal_person_type_category', models.CharField(blank=True, max_length=150, null=True)),
                ('register_place', models.CharField(blank=True, max_length=150, null=True)),
                ('register_number', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='legalPersonShareholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueIdentifier', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('position_type', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage_voting_right', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='legalPersonStakeholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueIdentifier', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('start_at', models.CharField(blank=True, max_length=150, null=True)),
                ('position_type', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_owner_signature', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('end_at', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UUid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
