# Generated by Django 4.1.13 on 2024-10-31 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'دیگر')], default='O', max_length=1)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('national_id', models.CharField(max_length=10)),
                ('chat_id_telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('seri_shenasname', models.CharField(blank=True, max_length=10, null=True)),
                ('seri_shenasname_char', models.CharField(blank=True, max_length=10, null=True)),
                ('serial_shenasname', models.CharField(blank=True, max_length=10, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('highschool', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], max_length=15, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='آدرس شرکت')),
                ('company_city_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='پیش شماره شهر شرکت')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن شرکت')),
                ('company_postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی شرکت')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل شرکت')),
                ('company_fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس شرکت')),
                ('company_fax_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='پیش شماره فکس شرکت')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان شغل')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='شرح شغل')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('is_current', models.BooleanField(default=True, verbose_name='شغل فعلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_infos', to='user.user')),
            ],
            options={
                'verbose_name': 'اطلاعات شغلی',
                'verbose_name_plural': 'اطلاعات شغلی',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('country_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='پیش شماره کشور')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('city_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='پیش شماره شهر')),
                ('section', models.CharField(max_length=100, verbose_name='بخش')),
                ('remnant_address', models.TextField(verbose_name='ادامه آدرس')),
                ('alley', models.CharField(blank=True, max_length=100, null=True, verbose_name='کوچه')),
                ('plaque', models.CharField(max_length=20, verbose_name='پلاک')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('emergency_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن اضطراری')),
                ('emergency_tel_city_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='پیش شماره شهر تلفن اضطراری')),
                ('emergency_tel_country_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='پیش شماره کشور تلفن اضطراری')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس')),
                ('fax_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='پیش شماره فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=255)),
                ('branch_code', models.CharField(max_length=10)),
                ('branch_name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('sheba_number', models.CharField(max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
