name: Space API CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: "root"
          SERVER_HOST: "31.40.4.92"
          SERVER_PORT: "2233"
          SERVER_DIR: "/var/www/space/api/"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SERVER_PORT -H $SERVER_HOST >> ~/.ssh/known_hosts
          
          scp -P $SERVER_PORT requirements.txt $SERVER_USER@$SERVER_HOST:$SERVER_DIR/
          
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST << EOF
            cd $SERVER_DIR || { echo "Failed to navigate to server directory"; exit 1; }
            

            rm -rf .git
            
            if [ ! -d ".git" ]; then
              git clone https://github.com/isatispooya/space-api.git . --quiet
            else
              git pull origin main || { echo "Git pull failed"; exit 1; }
            fi


            apt-get update && apt-get install -y python3-pip
            python3 -m pip install --upgrade pip
            
            # نصب requirements
            python3 -m pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
            python3 manage.py makemigrations || { echo "makemigrations failed"; exit 1; }
            python3 manage.py migrate || { echo "migrate failed"; exit 1; }
          EOF
